language: node_js
sudo: required
dist: trusty
node_js: '7'
env: CXX=g++-4.8
addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: g++-4.8
before_script: npm install -g gulp
script:
- gulp prep
before_deploy:
- mkdir deploy
- gulp travisZip
